New test for Tags Analysis
valeraparafin/asodesk_cy pull request #13
Opened 2023-07-07 10:28 UTC by IgorIvankov

2023-07-08 15:17 UTC, valeraparafin requested changes

2023-07-08 15:17 UTC, valeraparafin commented on integration/Smoke_suite/Env_is_alive/TA-is-alive.js
> +                expect(response.body.data).not.be.eq(0);
Добавить проверку на undefined

2023-07-08 15:19 UTC, valeraparafin commented on integration/Smoke_suite/Env_is_alive/TA-is-alive.js
> +    it('Versions" should response 200 and not be empty ', function () {
'Versions" should response 200 and not be empty '

лишние двойные кавычки убрать или добавить вторые

2023-07-08 15:19 UTC, valeraparafin commented on integration/Smoke_suite/Env_is_alive/TA-is-alive.js
> +    it('tag-analysis-statistics" should response 200 and not be empty ', function () {
идентично кавычки

2023-07-08 15:20 UTC, valeraparafin commented on integration/Smoke_suite/Env_is_alive/TA-is-alive.js
> +    it('tag-analysis-tags-report" should response 200 and not be empty ', function () {
идентично кавычки

2023-07-10 13:16 UTC, IgorIvankov commented on integration/Smoke_suite/Env_is_alive/TA-is-alive.js
> +                expect(response.body.data).not.be.eq(0);
Добавил

2023-07-10 13:16 UTC, IgorIvankov commented on integration/Smoke_suite/Env_is_alive/TA-is-alive.js
> +    it('tag-analysis-statistics" should response 200 and not be empty ', function () {
исправил

2023-07-10 13:16 UTC, IgorIvankov commented on integration/Smoke_suite/Env_is_alive/TA-is-alive.js
> +    it('tag-analysis-tags-report" should response 200 and not be empty ', function () {
Исправил

2023-07-10 13:23 UTC, valeraparafin approved these changes

2023-07-10 13:23 UTC, merged