New no auth tests
valeraparafin/asodesk_cy pull request #20
Opened 2023-11-17 07:47 UTC by IgorIvankov

2023-11-18 19:52 UTC, valeraparafin requested changes

2023-11-18 19:52 UTC, valeraparafin commented on integration/UI/No_Auth/NoAuth-DemoDataTools.js
> +    it('comparative-report-chart should response 200 and not be empty ', function () {
Давай вытащим все тесты апи в отдельную папку, назовём её API а в ней папку No_Auth и туда уйдут все апишные степы, которые не относятся к UI

2023-11-18 19:52 UTC, valeraparafin commented on integration/UI/No_Auth/NoAuth-FullAccessTools.js
> +    it('app-profile should response 200 and not be empty', function () {
Аналогично с апи степами

2023-11-18 19:52 UTC, valeraparafin commented on integration/UI/No_Auth/NoAuth-LimitedAccessTools.js
> +    it('top-charts free should respose 200 and not be empty', function () {
Аналогично с апи степами

2023-11-18 19:52 UTC, valeraparafin commented on integration/UI/No_Auth/NoAuth-RedirectToLoginPage.js
> +        cy.visit('http://hq.asodesk.com');
урл везде заменить на "/" или с какой целью используется хардкод с http?

2023-11-18 19:52 UTC, valeraparafin commented on integration/UI/No_Auth/NoAuth-DemoDataTools.js
> +        cy.on('uncaught:exception', (err, runnable) => {
Заменить эту конструкцию на во всех тестах на 
```javascript
beforeEach("Ignore 401", () => {
  // Ignore errors for unauthorized user (401)
  cy.on("uncaught:exception", (err) => {
    if (err.message.includes("401")) {
      return false;
    }
  });
});
```

2023-11-18 19:52 UTC, valeraparafin commented on integration/UI/No_Auth/NoAuth-DemoDataTools.js
> +        cy.on('uncaught:exception', (err, runnable) => {
Используется 1 раз перед всеми тестами в одном спек файле, не нужно добавлять в каждый тест

2023-11-18 19:52 UTC, valeraparafin commented on integration/UI/No_Auth/NoAuth-DemoDataTools.js
> +import { Runnable } from "mocha";
это тоже не нужно

2023-11-20 14:26 UTC, IgorIvankov commented on integration/UI/No_Auth/NoAuth-FullAccessTools.js
> +    it('app-profile should response 200 and not be empty', function () {
Сделал

2023-11-20 14:27 UTC, IgorIvankov commented on integration/UI/No_Auth/NoAuth-LimitedAccessTools.js
> +    it('top-charts free should respose 200 and not be empty', function () {
Сделал

2023-11-20 14:27 UTC, IgorIvankov commented on integration/UI/No_Auth/NoAuth-RedirectToLoginPage.js
> +        cy.visit('http://hq.asodesk.com');
Спасибо, так лучше. Не помню зачем хардкод вписал)

2023-11-20 14:28 UTC, IgorIvankov commented on integration/UI/No_Auth/NoAuth-DemoDataTools.js
> +        cy.on('uncaught:exception', (err, runnable) => {
Спасибо, так намного лучше

2023-11-20 14:28 UTC, IgorIvankov commented on integration/UI/No_Auth/NoAuth-DemoDataTools.js
> +import { Runnable } from "mocha";
Согласен, убрал

2023-11-20 17:27 UTC, valeraparafin approved these changes

2023-11-20 17:27 UTC, merged